language: node_js
node_js:
  - "stable"
install:
  - yarn install --frozen-lockfile
script:
  - yarn test
  - yarn build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID_PROD
    secret_access_key: $AWS_SECRET_ACCESS_KEY_PROD
    bucket: "eventing-production"
    skip_cleanup: true
    acl: public_read
    on:
      branch: master
  # - provider: s3
  #   access_key_id: "YOUR AWS ACCESS KEY"
  #   secret_access_key: "YOUR AWS SECRET KEY"
  #   bucket: "S3 Bucket"
  #   skip_cleanup: true
  #   acl: public_read
  #   on:
  #     branch: development
