language: node_js
node_js:
  - "stable"
install:
  - yarn install --frozen-lockfile
  - npm install -g @aws-amplify/cli
  - ./amplify-pull.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
script:
  - yarn test
  - yarn build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "eventing-production"
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "eventing-preprod"
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      branch: development
