language: node_js
node_js:
  - "stable"
install:
  - yarn install --frozen-lockfile
  - npm install -g @aws-amplify/cli
  - "
    AWSCLOUDFORMATIONCONFIG="{\
    \"configLevel\":\"project\",\
    \"useProfile\":false,\
    \"profileName\":\"default\",\
    \"accessKeyId\":\"headlessaccesskeyid\",\
    \"secretAccessKey\":\"headlesssecrectaccesskey\",\
    \"region\":\"us-east-1\"\
    }"
    PROVIDERS="{\
    \"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
    }"

    amplify pull \
    --providers $PROVIDERS \
    --yes
    "
script:
  - yarn test
  - yarn build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID_PROD
    secret_access_key: $AWS_SECRET_ACCESS_KEY_PROD
    bucket: "eventing-production"
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID_PREPROD
    secret_access_key: $AWS_SECRET_ACCESS_KEY_PREPROD
    bucket: "eventing-preprod"
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      branch: development
